import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const mergeClass = (class1: string, class2: string) => {
  return class1 + class2
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <title>Nikhils Page</title>
      </head>
      <body className={inter.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  )
}
